/**
 * Central Application Configuration
 * Auto-generated by Control Panel
 * Generated at: 2025-12-02T09:29:15.911Z
 */

// ============================================
// 1. SCHEDULER SETTINGS
// ============================================
export const SCHEDULER = {
  "ANALYST_REFRESH_CRON": "0 0 * * *",
  "TIMEZONE": "America/New_York",
  "ENABLED": false
};

// ============================================
// 2. BATCH PROCESSING SETTINGS
// ============================================
export const BATCH = {
  "PRICE_TARGET_BATCH_SIZE": 3,
  "PRICE_TARGET_BATCH_DELAY_MS": 1000,
  "DB_UPSERT_BATCH_SIZE": 1000,
  "FMP_PARALLEL_BATCH_SIZE": 4
};

// ============================================
// 3. API RATE LIMITS
// ============================================
export const RATE_LIMIT = {
  "FMP_REQUESTS_PER_MINUTE": 250,
  "FMP_WINDOW_MS": 60000,
  "API_TIMEOUT_MS": 30000,
  "MAX_RETRIES": 3,
  "INTER_REQUEST_DELAY_MS": 100
};

// ============================================
// 3-1. ADAPTIVE RATE LIMITING
// ============================================
export const ADAPTIVE_RATE = {
  // Legacy thresholds (kept for backward compatibility)
  "AGGRESSIVE_THRESHOLD": 0,
  "FAST_THRESHOLD": 0,
  "MODERATE_THRESHOLD": 0,
  "CAUTIOUS_THRESHOLD": 0,
  "AGGRESSIVE_BATCH_SIZE": 10,
  "FAST_BATCH_SIZE": 8,
  "MODERATE_BATCH_SIZE": 5,
  "CAUTIOUS_BATCH_SIZE": 3,
  "CRITICAL_BATCH_SIZE": 2,
  "AGGRESSIVE_DELAY_MS": 50,
  "FAST_DELAY_MS": 100,
  "MODERATE_DELAY_MS": 300,
  "CAUTIOUS_DELAY_MS": 500,
  "CRITICAL_DELAY_MS": 1000,
  
  // Throughput-based adaptive rate limiting
  "BATCH_SIZE": 10,                    // Default batch size
  "TARGET_REQUESTS_PER_MIN": 237,      // Target: 95% of 250/min limit
  "THROUGHPUT_WINDOW_SEC": 30,         // Measurement window (30 seconds)
  "INITIAL_DELAY_MS": 200,              // Initial delay between batches
  "MIN_DELAY_MS": 10,                   // Minimum delay (ms)
  "MAX_DELAY_MS": 2000,                 // Maximum delay (ms)
  
  // PID controller parameters
  "PID_KP": 50,                        // Proportional gain
  "PID_KI": 5,                         // Integral gain
  "PID_KD": 10,                        // Derivative gain
  "MAX_INTEGRAL": 100,                 // Anti-windup limit
  "DELAY_SMOOTHING": 0.3,              // Exponential smoothing factor (0-1)
  
  // Logging
  "LOG_INTERVAL": 10                   // Log every N requests
};

// ============================================
// 4. DATABASE QUERY LIMITS
// ============================================
export const DB_LIMITS = {
  "SYMBOL_CACHE": 100000,
  "ANALYST_RECORDS": 500000,
  "ANALYST_LOG": 100000,
  "TRADES": 100000,
  "MODEL_SUMMARIES": 10000
};

// ============================================
// 5. CACHE SETTINGS
// ============================================
export const CACHE = {
  SYMBOL_CACHE_DAYS: 7,
  SYMBOL_CACHE_MS: 7 * 24 * 60 * 60 * 1000
};

// ============================================
// 6. PRICE TREND HORIZONS
// ============================================
export const PRICE_TREND = {
  "HORIZONS": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    30,
    60,
    180,
    365
  ],
  "PRICE_FETCH_WINDOW_DAYS": 7
};

// ============================================
// 6-1. RETURN CAP SETTINGS (for Dashboard/Control UI)
// ============================================
export const RETURN_CAP = {
  "MAX_CAP_PCT": 0,
  "LOW_CAP_PCT": 0,
  "ENABLED": true
};

// ============================================
// 7. TABLE NAMES
// ============================================
export const TABLES = {
  "SYMBOL_CACHE": "symbol_cache",
  "EVENT_CACHE": "event_cache",
  "ANALYST_RECORDS": "analyst_records",
  "ANALYST_LOGS": "analyst_logs",
  "TRADES": "trades",
  "MODEL_SUMMARIES": "model_summaries",
  "MARKET_HOLIDAYS": "market_holidays",
  "EVENT_PATTERNS": "event_patterns",
  "PATTERN_SETTINGS": "pattern_settings"
};

// ============================================
// 7-1. MARKET HOLIDAYS SETTINGS
// ============================================
export const MARKET_HOLIDAYS = {
  "DEFAULT_EXCHANGE": "NASDAQ",
  "UPDATE_ON_STARTUP": true
};

// ============================================
// 8. API ENDPOINTS
// ============================================
export const ENDPOINTS = {
  "HEALTH": "/health",
  "GET_EVENT": "/getEvent",
  "GET_EVENT_LATEST": "/getEventLatest",
  "GET_VALUATION": "/getValuation",
  "REFRESH_ANALYST_LOG": "/refreshAnalystLog",
  "GENERATE_RATING": "/generateRating",
  "PRICE_TRACKER": "/priceTracker",
  "TRACKED_PRICE": "/trackedPrice",
  "CONTROL": "/control"
};

// ============================================
// EXPORT ALL CONFIG
// ============================================
export const APP_CONFIG = {
  SCHEDULER,
  BATCH,
  RATE_LIMIT,
  ADAPTIVE_RATE,
  DB_LIMITS,
  CACHE,
  PRICE_TREND,
  RETURN_CAP,
  TABLES,
  MARKET_HOLIDAYS,
  ENDPOINTS
};

export default APP_CONFIG;
